# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-15 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('bookmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=32)),
                ('publister_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE,
                                                   to='bookmanager.Publisher')),
            ],
        ),
    ]
